CC=g++
WORKROOT=../../../../
MAKEROOT=../
include ../include/makefile.env


INCLUDES=-I$(ULLIB_PATH)/include \
		-I$(MAKEROOT)/include\
		-I$(FILEBLOCK)/ \
		-I$(MAKEROOT)/lib -I$(ANS)/\
		-I$(CACHE_PATH)/include

CFLAGS = -Wall -W -pipe -Wno-unused-parameter -g -fPIC  -O2


LDFLAGS= -lm
OBJS=ri.o mg.o di.o cm.o bk.o bitset.o
LIB=libtscore.a

all : $(LIB)

%.o : %.cpp
	$(CC) $(CFLAGS) -c $< -o $@ $(INCLUDES)

$(LIB) : $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	rm -f $(OBJS)

tags : 
	 ctags -R *

clean:
	rm -f $(OBJS) $(TARGET) $(LIB)
