CC=g++

WORKROOT=../../../../
MAKEROOT=../
include ../include/makefile.env

INCLUDES=-I$(ULLIB_PATH)/include \
		-I${MAKEROOT}/include \
		-I$(MCPACK) -I$(MCPACK)/tools \
		-I$(NSHEAD)\
		-I$(DICT_PATH)/include \
		-I$(UBLIB)/include \
		-I${WORDSEG_PATH} \
		-I${TS_LIB_PATH} \
		-I$(NSFELT_PATH)/include \
		-I$(POSTAG_PATH)/include \
		-I$(CCODE_PATH)/include \
		-I$(OTHERS_EX_PATH)/include \
		-I${ANS} \
		-I${MAKEROOT}/lib

CFLAGS = -Wall -W -pipe -Wno-unused-parameter -g -fPIC -O3


LDFLAGS= -L$(WORDSEG_PATH) -lsegment -L$(DICT_PATH)/lib -luldict -L$(TS_LIB_PATH)/ -lutils -lm
OBJS=default.o tokenizer.o data_accessor.o 
LIB=libtshelper.a

all : $(LIB)

%.o : %.cpp
	$(CC) $(CFLAGS) -c $< -o $@ $(INCLUDES)

$(LIB) : $(OBJS)
	rm -f $@
	ar cr $@ $(OBJS)
	rm -f $(OBJS)

tags : 
	 ctags -R *

clean:
	rm -f $(OBJS) $(TARGET) $(LIB)
